Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using ProductManagementSystem.Models;
using ProductManagementSystem.Services;

namespace ProductManagementSystem.Controllers
{
    public class AdminController : Controller
    {
        private IProductRepository productRepository;
        private IFileUploadService fileUploadService;

        //constructor 
        public AdminController(IProductRepository productRepository, IFileUploadService fileUploadService) //service injection
        {
            this.productRepository = productRepository;
            this.fileUploadService = fileUploadService;
        }

        /// <summary>
        /// to display the main page for Admin Portal
        /// </summary>
        /// <returns>Admin Home view</returns>
        public IActionResult AdminHome()
        {
            AllProductsView allProductsView = new AllProductsView();
            allProductsView.Products = productRepository.GetRecords();
            return View(allProductsView);
        }

        /// <summary>
        /// to display the details view for the product with the passed id
        /// </summary>
        /// <param name="id">id of the product for wihich details need to be displayed</param>
        /// <returns>details view for the product with the passed id</returns>
        public IActionResult Details(int? id)
        {
            Product p = productRepository.GetRecord(id);
            if (p == null)
                return NotFound();
            return View(p);
        }
        /// <summary>
        /// To open the Add view where a new product can be added to the inventory
        /// </summary>
        /// <returns>open the Add product form page and passes a ViewBag with the max Id value 
        /// in our inventory to it</returns>
        [HttpGet]
        public IActionResult Add()
        {
            if(productRepository.MaxID()!=null)
                ViewBag.Max = productRepository.MaxID();
            else
                ViewBag.Max = 0;
            return View();
        }

        /// <summary>
        /// To submit a newly created product in the Add view's form so that it gets 
        /// added to the inventory
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Add(Product p, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if(await fileUploadService.UploadFile(file))
                {
                    p.Image = fileUploadService.FileName;
                }
                else
                {
                    ViewBag.ErrorMessage = "File upload failed";
                    p.Image = null;
                }
                productRepository.AddRecord(p);
                ViewBag.Message = "Successfully added product: "+ p.Name;
            }
            if (productRepository.MaxID() != null)
                ViewBag.Max = productRepository.MaxID();
            else
                ViewBag.Max = 0;
            return View(p);
        }

        /// <summary>
        /// To open the Edit view where you can edit a product's data
        /// </summary>
        /// <param name="id">id of the product to edit</param>
        /// <returns>Edit page view of passed id product</returns>
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            Product p=productRepository.GetRecord(id);
            if (p == null)
                return NotFound();
            return View(p);
        }

        [HttpPost]
        public IActionResult Edit(Product p)
        { 
            if(ModelState.IsValid)
            {
                productRepository.UpdateRecord(p);
                return RedirectToAction("AdminHome");
            }
            else
            {
                ViewBag.Message = "Error editing employee";
                return View(p);
            }
        }

        /// <summary>
        /// To delete a product
        /// </summary>
        public IActionResult Delete(int? id)
        {
            productRepository.DeleteRecord(id);
            return RedirectToAction("AdminHome");
        }
    }
}

Controllers/ProductController.cs
using ProductManagementSystem.Models;
using ProductManagementSystem.Services;
using Microsoft.AspNetCore.Mvc;

namespace ProductManagementSystem.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository productRepository;

        public ProductController(IProductRepository productRepository) //service injection
        {
            this.productRepository = productRepository;
        }

        public IActionResult DisplayAll()
        {
            AllProductsView allProductsView = new AllProductsView();
            allProductsView.Products = productRepository.GetRecords();
            return View(allProductsView);
        }
        public IActionResult Details(int? id)
        {
            Product p = productRepository.GetRecord(id);
            if(p == null)
                return NotFound();
            return View(p);
        }

    }
}

Views/Shared/ErrorDevelopment.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<img src="~/images/ohnodeveloper.gif" height="400" />


<h1 class="text-danger">Oh no! It's a developer's worst nightmare!
    <br />Looks like something went wrong
</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

<h3>NOTE: You are in Development Mode</h3>

Views/Shared/ErrorProduction.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">
    My sincerest apologies, dear User! 
    <br />There has been an error with this page!
</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

<h3>You are in Production Mode</h3>
<p>
    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

<img src="~/images/ohnoproduction.jpg" height="400" />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kitchie.com</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductManagementSystem.styles.css" asp-append-version="true" />
    <style>
        body{
            background-color: #f1f0cc;
        }
    </style>
</head>
<body>
    <header>
        <nav style="background-color:#3f0d12; color:#f1f0cc"
             class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/Kitchiepanlogonobackground.png" height="40"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Product" asp-action="DisplayAll">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Admin" asp-action="AdminHome">Admin</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" style="padding-right:20px">
                        <input name="searchstring" type="text" class="form-control" placeholder="Search on site..." />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - kitchie.com LLC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kitchie.com</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductManagementSystem.styles.css" asp-append-version="true" />
    <style>
        body {
            background-color: #caf0f8;
        }
    </style>
</head>
<body>
    <header>
        <nav style="background-color:#1d3557; color:#f1f0cc"
             class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/Kitchiepanlogonobackground.png" height="40" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Home" asp-action="Index">kitchie Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Admin" asp-action="AdminHome">Admin Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Admin" asp-action="Add">Add New Product</a>
                        </li>
                    </ul>
                    <div style="font-size:24px; padding-right:60px">ADMIN PORTAL</div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - kitchie.com LLC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutPrivacy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kitchie.com</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductManagementSystem.styles.css" asp-append-version="true" />
    <style>
        body{
            background-color: #f1f0cc;
        }
    </style>
</head>
<body>
    <header>
        <nav style="background-color:#3f0d12; color:#f1f0cc"
             class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/Kitchiepanlogonobackground.png" height="40"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Product" asp-action="DisplayAll">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:#eae2b7" asp-area="" asp-controller="Admin" asp-action="AdminHome">Admin</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" style="padding-right:20px">
                        <input name="searchstring" type="text" class="form-control" placeholder="Search on site..." />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - kitchie.com LLC 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>